version: "3.7"
services:
  app:
    build:
      args:
        user: hanun
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: perpus-laravel
    container_name: perpus-laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - perpus-laravel

  db:
    image: mysql:8.0
    container_name: perpus-laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: perpus-laravel
      MYSQL_ROOT_PASSWORD: hanun
      MYSQL_PASSWORD: hanun
      MYSQL_USER: hanun
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - perpus-laravel

  nginx:
    image: nginx:alpine
    container_name: perpus-laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - perpus-laravel

networks:
  perpus-laravel:
    driver: bridge
